# Generated by Django 5.2.2 on 2025-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('KHI', 'Karachi'), ('LHR', 'Lahore'), ('ISB', 'Islamabad'), ('RWP', 'Rawalpindi'), ('PEW', 'Peshawar'), ('QTA', 'Quetta'), ('MUX', 'Multan'), ('HYD', 'Hyderabad'), ('FSD', 'Faisalabad'), ('GJR', 'Gujranwala')], max_length=100),
        ),
    ]
