# Generated by Django 5.2.2 on 2025-06-08 07:19

import ckeditor.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
        migrations.AddField(
            model_name='car',
            name='province',
            field=models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory')], default='Sindh', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(default='Sedan', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(default='Car Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('KHI', 'Karachi'), ('LHR', 'Lahore'), ('ISB', 'Islamabad'), ('RWP', 'Rawalpindi'), ('PEW', 'Peshawar'), ('QTA', 'Quetta'), ('MUX', 'Multan'), ('HYD', 'Hyderabad'), ('FSD', 'Faisalabad'), ('GJR', 'Gujranwala')], default='KHI', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(default='Description of the car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='4', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(default='1.8L', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], default='Cruise Control', max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(default='First Owner', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_no',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025, verbose_name='year'),
        ),
    ]
