# Generated by Django 5.2.2 on 2025-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_state_car_province_alter_car_body_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
