# Generated by Django 5.2.2 on 2025-06-09 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character YouTube video ID.', regex='^[\\w-]{11}$')]),
        ),
    ]
